steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/taneli-anthos-sandbox/hello-app:$SHORT_SHA', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/taneli-anthos-sandbox/hello-app:$SHORT_SHA']
images: ['eu.gcr.io/taneli-anthos-sandbox/hello-app:$SHORT_SHA']