node {
    stage('Build') {
 
        checkout scm

        googleCloudBuild \
            credentialsId: 'taneli-anthos-sandbox',
            source: local('.'),
            request: file('hello-app/cloudbuild.yaml'),
            substitutions: [
                SHORT_SHA: "v${env.BUILD_ID}"
            ]
    }
}