node {
    stage('Build') {
 
        checkout scm

        googleCloudBuild \
            credentialsId: 'taneli-anthos-sandbox',
            source: local('src'),
            request: file('hello-app/cloudbuild.yaml')
    }
}